name: shared
description: "A new Flutter package project."
version: 0.0.1
homepage:
repository: https://github.com/CodeHiSmile/shared
issue_tracker: https://github.com/CodeHiSmile/shared/issues
documentation: https://github.com/CodeHiSmile/shared

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  timeago: ^3.7.1
  get_it: ^9.0.5
  crypto: ^3.0.7
  dio: ^5.9.0
  device_info_plus: ^12.2.0
  flutter_udid: ^4.0.0
  shared_preferences: ^2.5.3
  encrypt_shared_preferences: ^0.9.10
  injectable: ^2.5.1
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  tuple: ^2.0.2
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  flutter_image_compress: ^2.3.0
  photo_view: ^0.15.0
  connectivity_plus: ^6.1.0
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2
  permission_handler: ^12.0.1
  saver_gallery: ^4.1.0
  characters: ^1.4.0
  provider: ^6.1.5+1
  open_filex: ^4.7.0
  geocoding: ^4.0.0
  location: ^8.0.1
  share_plus: ^11.0.1
  decimal: ^2.3.3
  rxdart: ^0.28.0
  android_id: ^0.4.0
  fluttertoast: ^8.2.8
  flutter_gen_runner: ^5.12.0
  freezed_annotation: ^3.1.0
  mime: ^2.0.0
  async: ^2.13.0
  dartx: ^1.2.0
  logging: ^1.3.0

  #Encryption packages
  encrypt: ^5.0.3
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.3
  freezed: ^3.2.3
  injectable_generator: ^2.7.0
